[build]
  command = "npm run build:ui"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  VITE_DEMO_MODE = "true"
  # Backend on Vercel Serverless (Railway no longer used - migrated Oct 2025)
  VITE_API_URL = "https://ai-dawg-deploy-g1ort01sz-bens-projects-4e60e0da.vercel.app/api"
  VITE_WEBSOCKET_URL = "https://ai-dawg-deploy-g1ort01sz-bens-projects-4e60e0da.vercel.app"
  VITE_AI_BRAIN_URL = "https://ai-dawg-deploy-g1ort01sz-bens-projects-4e60e0da.vercel.app"
  VITE_REALTIME_VOICE_URL = "https://ai-dawg-deploy-g1ort01sz-bens-projects-4e60e0da.vercel.app"
