[build]
  command = "npm run build:ui"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  VITE_DEMO_MODE = "true"
  VITE_API_URL = "/api/v1"
